
-- CREATE TABLE ADDRESS_POOL (
--     MGT_NO            VARCHAR(25)
--   , ROAD_CODE         CHAR(12)
--   , EMD_SEQ           VARCHAR(2)
--   , BASEMENT          BOOLEAN
--   , BD_MAIN_NO        INTEGER (5) UNSIGNED
--   , BD_SUB_NO         INTEGER (5) UNSIGNED
--   , ZIP5_CODE         CHAR(5)
--   , CHANGE_CODE       CHAR(2)
--   , NOTIFICATION_DATE VARCHAR(8)
--   , BF_ROAD_ADDR      VARCHAR(25)
--   , DET_ADDR          BOOLEAN
-- );
--
-- CREATE TABLE ADDRESS_JIBUN_POOL (
--     MGT_NO          VARCHAR(25)
--   , SNO             INTEGER (3) UNSIGNED
--   , LEGAL_DONG_CODE CHAR(10)
--   , SD_NAME         VARCHAR(20)
--   , SGG_NAME        VARCHAR(20)
--   , LEGAL_EMD_NAME  VARCHAR(20)
--   , LEGAL_LI_NAME   VARCHAR(20)
--   , MOUNTAIN        BOOLEAN
--   , LAND_MAIN_NO    INTEGER (4) UNSIGNED
--   , LAND_SUB_NO     INTEGER (4) UNSIGNED
--   , REPRESENTABLE   BOOLEAN
-- );
--
-- CREATE TABLE ADDRESS_EXTRA_POOL (
--     MGT_NO              VARCHAR(25)
--   , POLITICAL_DONG_CODE CHAR(10)
--   , POLITICAL_DONG_NAME VARCHAR(20)
--   , ZIP5_CODE           CHAR(5)
--   , ZIP_SNO             VARCHAR(3)
--   , MASS_ADDRESSEE_NAME VARCHAR(40)
--   , BD_NAME             VARCHAR(40)
--   , SGG_BD_NAME         VARCHAR(200)
--   , APARTMENT           BOOLEAN
-- );
--
-- CREATE TABLE ADDRESS_ROAD_POOL (
--     ROAD_CODE         CHAR(12)
--   , ROAD_NAME         VARCHAR(80)
--   , RAOD_ENAME        VARCHAR(80)
--   , EMD_SNO           VARCHAR(2)
--   , SD_NAME           VARCHAR(20)
--   , SD_ENAME          VARCHAR(40)
--   , SGG_NAME          VARCHAR(20)
--   , SGG_ENAME         VARCHAR(40)
--   , EMD_NAME          VARCHAR(20)
--   , EMD_ENAME         VARCHAR(40)
--   , EMD_CODE          CHAR(1)
--   , LEGAL_EMD_CODE    CHAR(3)
--   , ENABLED           BOOLEAN
--   , CHANGE_CODE       CHAR(1)
--   , CHANGE_HISTORY    VARCHAR(14)
--   , NOTIFICATION_DATE VARCHAR(8)
--   , ERASURE_DATE      VARCHAR(8)
-- );

INSERT INTO BUILDING(ADDRESS_ID, COMPOSITION_BASEMENT_FLOOR, COMPOSITION_GROUND_FLOOR, COMPOSITION_TYPE, AREA_PY, AREA_M2) VALUES ('1168010700105150000011929', '40', '3', '', 12345.67, 34567.89);
INSERT INTO BUILDING(ADDRESS_ID, COMPOSITION_BASEMENT_FLOOR, COMPOSITION_GROUND_FLOOR, COMPOSITION_TYPE, AREA_PY, AREA_M2) VALUES ('1168011100105920000000001', '13', '2', '', 12345.67, 34567.89);
INSERT INTO BUILDING(ADDRESS_ID, COMPOSITION_BASEMENT_FLOOR, COMPOSITION_GROUND_FLOOR, COMPOSITION_TYPE, AREA_PY, AREA_M2) VALUES ('1168010400100720008018751', '38', '1', '', 12345.67, 34567.89);
INSERT INTO BUILDING(ADDRESS_ID, COMPOSITION_BASEMENT_FLOOR, COMPOSITION_GROUND_FLOOR, COMPOSITION_TYPE, AREA_PY, AREA_M2) VALUES ('1168010800100560014026445',  '9', '5', '', 12345.67, 34567.89);
INSERT INTO BUILDING(ADDRESS_ID, COMPOSITION_BASEMENT_FLOOR, COMPOSITION_GROUND_FLOOR, COMPOSITION_TYPE, AREA_PY, AREA_M2) VALUES ('1168010800102060003009144', '11', '1', '', 12345.67, 34567.89);
INSERT INTO BUILDING(ADDRESS_ID, COMPOSITION_BASEMENT_FLOOR, COMPOSITION_GROUND_FLOOR, COMPOSITION_TYPE, AREA_PY, AREA_M2) VALUES ('1168010800100990010005179', '16', '7', '', 12345.67, 34567.89);
INSERT INTO BUILDING(ADDRESS_ID, COMPOSITION_BASEMENT_FLOOR, COMPOSITION_GROUND_FLOOR, COMPOSITION_TYPE, AREA_PY, AREA_M2) VALUES ('1168010400100790015017332',  '9', '5', '', 12345.67, 34567.89);
INSERT INTO BUILDING(ADDRESS_ID, COMPOSITION_BASEMENT_FLOOR, COMPOSITION_GROUND_FLOOR, COMPOSITION_TYPE, AREA_PY, AREA_M2) VALUES ('1168011000105200000005008', '17', '8', '', 12345.67, 34567.89);
INSERT INTO BUILDING(ADDRESS_ID, COMPOSITION_BASEMENT_FLOOR, COMPOSITION_GROUND_FLOOR, COMPOSITION_TYPE, AREA_PY, AREA_M2) VALUES ('1168010700106290015000001', '15', '6', '', 12345.67, 34567.89);
INSERT INTO BUILDING(ADDRESS_ID, COMPOSITION_BASEMENT_FLOOR, COMPOSITION_GROUND_FLOOR, COMPOSITION_TYPE, AREA_PY, AREA_M2) VALUES ('1168010700106500003000001', '14', '5', '', 12345.67, 34567.89);
INSERT INTO BUILDING(ADDRESS_ID, COMPOSITION_BASEMENT_FLOOR, COMPOSITION_GROUND_FLOOR, COMPOSITION_TYPE, AREA_PY, AREA_M2) VALUES ('1168010500101270000016609', '15', '7', '', 12345.67, 34567.89);
INSERT INTO BUILDING(ADDRESS_ID, COMPOSITION_BASEMENT_FLOOR, COMPOSITION_GROUND_FLOOR, COMPOSITION_TYPE, AREA_PY, AREA_M2) VALUES ('1168010800100010001000001', '20', '8', '', 12345.67, 34567.89);
INSERT INTO BUILDING(ADDRESS_ID, COMPOSITION_BASEMENT_FLOOR, COMPOSITION_GROUND_FLOOR, COMPOSITION_TYPE, AREA_PY, AREA_M2) VALUES ('1168010500101620011027783', '41', '4', '', 12345.67, 34567.89);
INSERT INTO BUILDING(ADDRESS_ID, COMPOSITION_BASEMENT_FLOOR, COMPOSITION_GROUND_FLOOR, COMPOSITION_TYPE, AREA_PY, AREA_M2) VALUES ('1168010700106660006010334', '12', '4', '', 12345.67, 34567.89);
INSERT INTO BUILDING(ADDRESS_ID, COMPOSITION_BASEMENT_FLOOR, COMPOSITION_GROUND_FLOOR, COMPOSITION_TYPE, AREA_PY, AREA_M2) VALUES ('1168010700106300031010878', '12', '4', '', 12345.67, 34567.89);
INSERT INTO BUILDING(ADDRESS_ID, COMPOSITION_BASEMENT_FLOOR, COMPOSITION_GROUND_FLOOR, COMPOSITION_TYPE, AREA_PY, AREA_M2) VALUES ('1168011000104420000004817',  '9', '3', '', 12345.67, 34567.89);
INSERT INTO BUILDING(ADDRESS_ID, COMPOSITION_BASEMENT_FLOOR, COMPOSITION_GROUND_FLOOR, COMPOSITION_TYPE, AREA_PY, AREA_M2) VALUES ('1168010100107200012000001', '19', '7', '', 12345.67, 34567.89);
INSERT INTO BUILDING(ADDRESS_ID, COMPOSITION_BASEMENT_FLOOR, COMPOSITION_GROUND_FLOOR, COMPOSITION_TYPE, AREA_PY, AREA_M2) VALUES ('1168010700105670015010614', '21', '5', '', 12345.67, 34567.89);
INSERT INTO BUILDING(ADDRESS_ID, COMPOSITION_BASEMENT_FLOOR, COMPOSITION_GROUND_FLOOR, COMPOSITION_TYPE, AREA_PY, AREA_M2) VALUES ('1168010500101000001017111', '17', '7', '', 12345.67, 34567.89);
INSERT INTO BUILDING(ADDRESS_ID, COMPOSITION_BASEMENT_FLOOR, COMPOSITION_GROUND_FLOOR, COMPOSITION_TYPE, AREA_PY, AREA_M2) VALUES ('1168010700106400000009715', '15', '4', '', 12345.67, 34567.89);
INSERT INTO BUILDING(ADDRESS_ID, COMPOSITION_BASEMENT_FLOOR, COMPOSITION_GROUND_FLOOR, COMPOSITION_TYPE, AREA_PY, AREA_M2) VALUES ('1168010800102030000000001',  '7', '4', '', 12345.67, 34567.89);


INSERT INTO CONTACT(FULLNAME, POSITION, EMAIL, MOBILE_NO, COMPANY_NAME) VALUES ('박찬석', '과장', 'pcspapa@gmail.com', '010-1234-5678', '실업');
INSERT INTO CONTACT(FULLNAME, POSITION, EMAIL, MOBILE_NO, COMPANY_NAME) VALUES ('정우성', '사장', 'dntjd@gmail.com', '010-2345-6789', '법인');
INSERT INTO CONTACT(FULLNAME, POSITION, EMAIL, MOBILE_NO, COMPANY_NAME) VALUES ('성창기', '차장', 'ckdrl@gmail.com', '010-3456-7890', '교보');
INSERT INTO CONTACT(FULLNAME, POSITION, EMAIL, MOBILE_NO, COMPANY_NAME) VALUES ('류석호', '대리', 'tjrgh@gmail.com', '010-4567-8901', '국민');
INSERT INTO CONTACT(FULLNAME, POSITION, EMAIL, MOBILE_NO, COMPANY_NAME) VALUES ('백대영', '사장', 'eodud@gmail.com', '010-5678-9012', '정호');
INSERT INTO CONTACT(FULLNAME, POSITION, EMAIL, MOBILE_NO, COMPANY_NAME) VALUES ('황윤수', '차장', 'dbstn@gmail.com', '010-6789-0123', '웅징');
INSERT INTO CONTACT(FULLNAME, POSITION, EMAIL, MOBILE_NO, COMPANY_NAME) VALUES ('전은석', '과장', 'dmstjr@gmail.com', '010-7890-1234', '학교');
INSERT INTO CONTACT(FULLNAME, POSITION, EMAIL, MOBILE_NO, COMPANY_NAME) VALUES ('한민성', '사장', 'alstjd@gmail.com', '010-8901-2345', '청소');
INSERT INTO CONTACT(FULLNAME, POSITION, EMAIL, MOBILE_NO, COMPANY_NAME) VALUES ('이재민', '부장', 'woals@gmail.com', '010-9012-3456', '음식');




-- CREATE TABLE MOLIT_BASIC (
--       MGM_BLDRGST_PK     VARCHAR(33)
--     , MGM_UP_BLDRGST_PK  VARCHAR(33)
--     , REGSTR_GB_CD       VARCHAR(1)
--     , REGSTR_GB_CD_NM    VARCHAR(100)
--     , REGSTR_KIND_CD     VARCHAR(1)
--     , REGSTR_KIND_CD_NM  VARCHAR(100)
--     , PLAT_PLC           VARCHAR(500)
--     , NEW_PLAT_PLC       VARCHAR(400)
--     , BLD_NM             VARCHAR(100)
--     , SIGUNGU_CD         VARCHAR(5)
--     , BJDONG_CD          VARCHAR(5)
--     , PLATGB_CD          CHAR(1)
--     , BUN                VARCHAR(4)
--     , JI                 VARCHAR(4)
--     , SPLOT_NM           VARCHAR(200)
--     , BLOCK              VARCHAR(20)
--     , LOT                VARCHAR(20)
--     , BYLOT_CNT          NUMERIC(5)
--     , NA_ROAD_CD         VARCHAR(12)
--     , NA_BJDONG_CD       VARCHAR(5)
--     , NA_UGRND_CD        VARCHAR(1)
--     , NA_MAIN_BUN        NUMERIC(5)
--     , NA_SUB_BUN         NUMERIC(5)
--     , JIYUK_CD           VARCHAR(6)
--     , JIGU_CD            VARCHAR(6)
--     , GUYUK_CD           VARCHAR(6)
--     , JIYUK_CD_NM        VARCHAR(100)
--     , JIGU_CD_NM         VARCHAR(100)
--     , GUYUK_CD_NM        VARCHAR(100)
--     , CRTN_DAY           VARCHAR(8)
-- );
--
-- LOAD DATA INFILE "/Users/cspark/Documents/realestate/data_utf8.txt"
-- INTO TABLE realestate.MOLIT_BASIC FIELDS TERMINATED BY "|";
--
--
-- SELECT * INTO OUTFILE '/Users/cspark/Documents/realestate/data_utf8.txt'
-- FIELDS TERMINATED BY '|'
-- FROM realestate.MOLIT_BASIC;
--
--
-- ALTER TABLE MOLIT_BASIC ADD CONSTRAINT PK_MOLIT_BASIC PRIMARY KEY ( MGM_BLDRGST_PK );
--
-- ALTER TABLE ADDRESS_POOL ADD CONSTRAINT FK_ADDRESS_ROAD_POOL FOREIGN KEY ( ROAD_CODE, EMD_SEQ ) REFERENCES ADDRESS_ROAD_POOL (ROAD_CODE, EMD_SNO);
--
-- ALTER TABLE MOLIT_BASIC DROP INDEX IDX_MOLIT_BASIC_ADDRESS;
--
-- ALTER TABLE MOLIT_BASIC ADD INDEX IDX_MOLIT_BASIC_ADDRESS (REGSTR_GB_CD, REGSTR_KIND_CD, NA_ROAD_CD, NA_BJDONG_CD, NA_MAIN_BUN, NA_SUB_BUN, NA_UGRND_CD);
--
-- ALTER TABLE MOLIT_BASIC ADD INDEX IDX_MOLIT_BASIC_MGM_UP_BLDRGST_PK (MGM_UP_BLDRGST_PK);
--
--
--
-- -- 자식이 없는 부모 삭제.
-- DELETE D
-- FROM   MOLIT_BASIC D
-- INNER JOIN (
-- SELECT *
-- FROM   (
-- SELECT P.MGM_BLDRGST_PK P_PK
--      , C.MGM_BLDRGST_PK C_PK
--      , C.MGM_UP_BLDRGST_PK C_P_PK
-- FROM MOLIT_BASIC  P
-- LEFT OUTER JOIN MOLIT_BASIC C
-- ON   P.MGM_BLDRGST_PK = C.MGM_UP_BLDRGST_PK
-- WHERE P.MGM_UP_BLDRGST_PK = '') T
-- WHERE T.C_PK IS NULL) C
-- WHERE D.MGM_BLDRGST_PK = C.P_PK;
--
--
--
--
-- CREATE TABLE MOLIT_TITLE_PART (
--       MGM_BLDRGST_PK           VARCHAR(33)
--     , REGSTR_GB_CD             VARCHAR(1)
--     , REGSTR_GB_CD_NM          VARCHAR(100)
--     , REGSTR_KIND_CD           VARCHAR(1)
--     , REGSTR_KIND_CD_NM        VARCHAR(100)
--     , PLAT_PLC                 VARCHAR(500)
--     , NEW_PLAT_PLC             VARCHAR(400)
--     , BLD_NM                   VARCHAR(100)
--     , SIGUNGU_CD               VARCHAR(5)
--     , BJDONG_CD                VARCHAR(5)
--     , PLAT_GB_CD               VARCHAR(1)
--     , BUN                      VARCHAR(4)
--     , JI                       VARCHAR(4)
--     , SPLOT_NM                 VARCHAR(200)
--     , BLOCK                    VARCHAR(20)
--     , LOT                      VARCHAR(20)
--     , BYLOT_CNT                NUMERIC(5)
--     , NA_ROAD_CD               VARCHAR(12)
--     , NA_BJDONG_CD             VARCHAR(5)
--     , NA_UGRND_CD              VARCHAR(1)
--     , NA_MAIN_BUN              NUMERIC(5)
--     , NA_SUB_BUN               NUMERIC(5)
--     , DONG_NM                  VARCHAR(100)
--     , MAIN_ATCH_GB_CD          CHAR(1)
--     , MAIN_ATCH_GB_CD_NM       VARCHAR(100)
--     , PLAT_AREA                NUMERIC(19,9)
--     , ARCH_AREA                NUMERIC(19,9)
--     , BC_RAT                   NUMERIC(19,9)
--     , TOT_AREA                 NUMERIC(19,9)
--     , VL_RAT_ESTM_TOT_AREA     NUMERIC(19,9)
--     , VL_RAT                   NUMERIC(19,9)
--     , STRCT_CD                 VARCHAR(2)
--     , STRCT_CD_NM              VARCHAR(100)
--     , ETC_STRCT                VARCHAR(500)
--     , MAIN_PURPS_CD            VARCHAR(5)
--     , MAIN_PURPS_CD_NM         VARCHAR(100)
--     , ETC_PURPS                VARCHAR(500)
--     , ROOF_CD                  VARCHAR(2)
--     , ROOF_CD_NM               VARCHAR(100)
--     , ETC_ROOF                 VARCHAR(500)
--     , HHLD_CNT                 NUMERIC(5)
--     , FMLY_CNT                 NUMERIC(5)
--     , HEIT                     NUMERIC(19,9)
--     , GRND_FLR_CNT             NUMERIC(5)
--     , UGRND_FLR_CNT            NUMERIC(5)
--     , RIDE_USE_ELVT_CNT        NUMERIC(5)
--     , EMGEN_USE_ELVT_CNT       NUMERIC(5)
--     , ATCH_BLD_CNT             NUMERIC(5)
--     , ATCH_BLD_AREA            NUMERIC(19,9)
--     , TOT_DONG_TOT_AREA        NUMERIC(19,9)
--     , INDR_MECH_UTCNT          NUMERIC(6)
--     , INDR_MECH_AREA           NUMERIC(19,9)
--     , OUDR_MECH_UTCNT          NUMERIC(6)
--     , OUDR_MECH_AREA           NUMERIC(19,9)
--     , INDR_AUTO_UTCNT          NUMERIC(6)
--     , INDR_AUTO_AREA           NUMERIC(19,9)
--     , OUDR_AUTO_UTCNT          NUMERIC(6)
--     , OUDR_AUTO_AREA           NUMERIC(19,9)
--     , PMS_DAY                  VARCHAR(8)
--     , STCNS_DAY                VARCHAR(8)
--     , USEAPR_DAY               VARCHAR(8)
--     , PMSNO_YEAR               VARCHAR(4)
--     , PMSNO_KIK_CD             CHAR(7)
--     , PMSNO_KIK_CD_NM          VARCHAR(100)
--     , PMSNO_GB_CD              VARCHAR(4)
--     , PMSNO_GB_CD_NM           VARCHAR(100)
--     , HO_CNT                   NUMERIC(5)
--     , ENGR_GRADE               VARCHAR(4)
--     , ENGR_RAT                 NUMERIC(19,9)
--     , ENGR_EPI                 NUMERIC(5)
--     , GN_BLD_GRADE             CHAR(1)
--     , GN_BLD_CERT              NUMERIC(5)
--     , ITG_BLD_GRADE            CHAR(1)
--     , ITG_BLD_CERT             NUMERIC(5)
--     , CRTN_DAY                 VARCHAR(8)
-- );
--
--
-- LOAD DATA INFILE "/Users/cspark/Documents/realestate/data_utf8.txt" IGNORE
-- INTO TABLE realestate.MOLIT_TITLE_PART
-- CHARACTER SET UTF8
-- FIELDS TERMINATED BY "|";
